### ISSUE TITLE
Nibe F750 outdoor and avg. Outdoor temperature stuck at 4°C.

### ISSUE THREAD

**Issue by Segran** [jaroschek/home-assistant-myuplink#161]
Since somtime the Home Assistant Nibe Uplink is showing a rock solid 4°C for both outdoor temperature and average outdoor temperature. On the F750 unit the correct outdoor temperature is shown. 

I have the latest fw in the F750 and Home Assistant release 2024.09.1.

pls advice

**Comment by jaroschek** [comment]
@Segran Have you checked the actual response values of the myUplink API as suggested here: https://github.com/jaroschek/home-assistant-myuplink#debugging-misbehaving-entities

> If the your entities are malformed, it's often caused by the manufacturer's implementation of the myUpLink-API. The easiest way to check this is by getting the raw data points from the Swagger client.
>
> 1. Take note of the entity's name, and open [myUpLink's Swagger](https://api.myuplink.com/swagger/index.html).
> 2. Click Authorize and paste your application credentials. Make sure to check the READSYSTEM box.
> 3. Find your device ID by querying `​/v2​/systems​/me`, and enter it when querying `/v2/devices/{deviceId}/points`.
Find the relevant data points and post them in an issue.

If the values do not change there too, this is caused by the myUplink API. The only solution would be to contact myUplink/Nibe to xplain/solve your issue.

But if the value in the myUplink API is different to the value shown in the Home Assistant integration the issue seems to be within the integration. If this is the case please take a look at the device connectivity (a diagnostic device entity) of your Nibe device in Home Assistant.

**Comment by Segran** [comment]
In fact, when  the other temperatures I found that all values are completely frozen, haven’t changed even 0,01°C in three days…..

**Comment by jaroschek** [comment]
Ok. That is strange. The entities should show, what the API provides. It seems that the myUplink integration is stuck. Do you have any error messages in the logs? 

What Version of this integration are you using in what version of Home Assistant? When did you restart your Home Assistant instance the last time?

**Comment by Segran** [comment]
The integration is 1.7.1, Home Assistant is 2024.9.1.  I restarted it several times today.  The only error massage I have in the logs related to Nibe is a warning that it takes more than 10 seconds to load/initiate. That warning is normal, it has always been like that.Should I delete the integration and install it again?Skickat från min iPad25 sep. 2024 kl. 20:47 skrev Stefan Jaroschek ***@***.***>:﻿
Ok. That is strange. The entities should show, what the API provides. It seems that the myUplink integration is stuck. Do you have any error messages in the logs?
What version of this integration are you using in what version of Home Assistant? When did you restart your Home Assistant instance the last time?

**Comment by jaroschek** [comment]
@Segran The latest version of this integration here is 1.5.0. Can you please take a screenshot of your integration status page?

This is how it looks in my installation with the latest version installed:
![image](https://github.com/user-attachments/assets/f594a90a-6e1d-474a-bd09-5994a3052e8e)

You can also temporarily enable the debug logging for this integration. After that reload the configured entry and wait about 15 minutes. Then deactivate the debug logging. This will lead to a download of the debug logs for this integration.

Since when are you using my integration from https://github.com/jaroschek/home-assistant-myuplink? 

Did you use the core integration from https://github.com/home-assistant/core/blob/dev/homeassistant/components/myuplink before or in between? (There are already issues related to the later core integration with the same domain `myuplink` as mine. This core integration was added in January 2024 while I developed this integration here in August 2022. #93 #61)

**Comment by Segran** [comment]
﻿Oh shit…. Stupid, stupid, stupid….. after a system crash I restored my NAS from backups and obviously I had selected a backup for Home Assistant from 2023, not 2024…. I got Nibe Uplink, not Nibe MyUplink….I am extremely embarassed and sorry for waisting your time. Thanks for helping my see my mistake.Best Regards,Göran ASkickat från min iPad26 sep. 2024 kl. 05:32 skrev Stefan Jaroschek ***@***.***>:﻿
@Segran The latest version of this integration here is 1.5.0. Can you please take a screenshot of your integration status page?
This is how it looks in my installation with the latest version installed:
image.png (view on web)
You can also temporarily enable the debug logging for this integration. After that reload the configured entry and wait about 15 minutes. Then deactivate the debug logging. This will lead to a download of the debug logs for this integration.
Since when are you using my integration from https://github.com/jaroschek/home-assistant-myuplink?
Did you use the core integration from https://github.com/home-assistant/core/blob/dev/homeassistant/components/myuplink before or in between? (There are already issues related to the later core integration with the same domain myuplink as mine. This core integration was added in January 2024 while I developed this integration here in August 2022. #93 #61)
