### ISSUE TITLE
Error while configuring the plugin

### ISSUE THREAD

**Issue by Minka24** [jaroschek/home-assistant-myuplink#24]
After an update to the newest version of the integration HA was not able to load the integration after a restart.

So I decided to uninstall the myuplink HACS integration. While configuring the new instance the UI throws an error `{"message":"Invalid handler specified"} ` and the logs showed an more detailed error as well:

```
ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration myuplink: cannot import name 'StrEnum' from 'enum' (/usr/local/lib/python3.10/enum.py)
```

Is there an issue with my HA instance or is the bug in the newest version of the integration?

**Comment by jaroschek** [comment]
This problem is cause, when you are not using python 3.10 for HA. I recently followed the recommendation to replace the backported `StrEnum`.

This was the advice that was given:
```
StrEnum is deprecated, We can now use the Python 3.11 provided enum.StrEnum insteadpylint(hass-deprecated-import)
```

But as I realize now, it can not be guaranteed that everybody switches to Python 3.11 instantly. So I will revert this change and restore the backported `StrEnum`.

**Comment by jaroschek** [comment]
@Minka24 The backported `StrEnum` is now restored and merged into main. When you update the integration it will work again.

**Comment by Minka24** [comment]
Thanks for the very fast response. I’ll try later to update the integration.
